travis:
  secure:
    BINSTAR_TOKEN: BoQVJ7oXUrdDyVZrx8UOsQsbb+5rEbqBepE1H3ZxyYRo39ncxEmHTej8AdnLDe57Bz9ccYt18sHAi+celjNxrSpiDpt39bx8cFFuV4F+RsQ2Jf4xXYvmDGicm3UVs1KEAMGJs+OscDcQ54VZAhCEowM8dQ5h/kPRrdKQe56fVjgLphcyDikIlyPO24tslxac2GHwBdWewJfjDOvJegyfU0IFD/iG8jr27MD6kmaAucuQ9NK/CTTJ4moT7Uw+Xxip6E/IClgKCricKFrQWwFjDcD0v2d04PTpYdzz2oSfSKiyB3aafBBZYp/WgijdJ7k56mdW5LEjaNzN3INgvoL10Enp5DYVpbHKkApG9GtmLXVOO1SLXnvB9Bf0OqW/Q13M0ZtvbHWX86gOrlMdXmVXp/Ik424K8K8JfvqUf2sUSrZi9wiAVEKmxni3/A/zoSAfUNd6uQ8TOLTk10CO6AP3BrA/5bOdLN1LYtXIyQozAYPnEK9DBE9wDcGsDCsiI+SIY5Mkfib2MPwsvou64iFg7cNE2c6qjTP77FkW6lJZQOlO5+INqz7wZ2rREZ3lEg3X3oX0Qwxm+K4GjYT+47/aRrcPAXyObUbI4Dq4Wju+zMgsPGGHcIk1NgxVI0jSz+j/8MKv3br8sy1wXnHgtxuISz9Jgc0YevegBsjlagcLkwE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
